/* Deterministic local regression and screenshot harness. No test hooks ship in index.html. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),vm=require('node:vm');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');new vm.Script(html.slice(html.indexOf('<script>')+8,html.lastIndexOf('</script>')));new vm.Script(fs.readFileSync(path.join(root,'constellation-sw.js'),'utf8'));JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const results={accessibility:[],checks:[],screenshots:[],errors:[],overflow:[],performance:[]};
const check=(name,ok,details)=>{assert.ok(ok,name+': '+JSON.stringify(details));results.checks.push({name,pass:true,details});console.log('PASS',name)};
const server=http.createServer((q,r)=>{const url=new URL(q.url,'http://localhost');if(url.pathname==='/seed'){r.setHeader('Content-Type','text/html');return r.end('<!doctype html><title>Test fixture</title>')}let f=path.join(root,url.pathname==='/'?'index.html':url.pathname);if(!f.startsWith(root)){r.statusCode=403;return r.end()}try{r.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.js')?'application/javascript':f.endsWith('.webmanifest')?'application/manifest+json':f.endsWith('.png')?'image/png':'text/plain');r.end(fs.readFileSync(f))}catch{r.statusCode=404;r.end()}});
const titles=['The art of learning','Deliberate practice','Attention and memory','Spaced repetition','Ask better questions','Working memory','Read the evidence','Learning journal','Research synthesis','Practice with feedback','A useful counterexample','Design the experiment','Knowledge grows together','Tomorrow’s reading','Is retrieval enough?','Build a daily habit','Compare the alternatives','Learning in community','A source worth revisiting','Make the connections'];
const types=['project','idea','concept','theorem','question','formula','paper','note','claim','task','example','task','idea','source','question','habit','decision','person','source','evidence'];
async function seed(page,count=20){await page.goto(base+'/seed');await page.evaluate(async({count,titles,types})=>{const req=indexedDB.open('constellation',2);const db=await new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});const tx=db.transaction(['nodes','edges','settings','groups'],'readwrite');for(const n of ['nodes','edges','groups'])tx.objectStore(n).clear();const colors=[[214,189,137],[136,182,155],[204,140,115],[130,171,189],[182,157,181]],ts=Date.now();for(let i=0;i<count;i++){const cols=count>20?Math.ceil(Math.sqrt(count)):5,row=Math.floor(i/cols),col=i%cols;tx.objectStore('nodes').put({id:'fixture-'+i,workspaceId:'workspace-default',title:titles[i%titles.length]+(count>20?' '+i:''),body:'A connected research note.\n\nUnderstanding develops through careful reading, deliberate practice, and useful feedback.\n\n- Ask a precise question\n- Test an explanation\n- Reflect on the result',type:types[i%types.length],position:{x:300+col*195,y:190+row*165,z:0},velocity:{x:0,y:0},appearance:{shape:'star',color:colors[i%5],size:1,opacity:1,icon:''},tags:['learning',i%2?'research':'practice'],groupIds:[],fields:{},status:i%4===0?'active':null,priority:i%3===0?'high':null,progress:i%4===0?35:null,dates:{start:null,due:null},flags:{pinned:false,locked:false,archived:false,favorite:i===0,private:false},source:i%types.length===6?{url:'https://example.com/paper',title:'Research notes',author:'Example author'}:null,attachments:[],metadata:{},createdAt:ts,updatedAt:ts,lastViewedAt:null});if(i)tx.objectStore('edges').put({id:'edge-'+i,workspaceId:'workspace-default',sourceId:'fixture-'+(i-1),targetId:'fixture-'+i,type:i%3===0?'supports':'related to',direction:'directed',style:'solid',geometry:'straight',color:null,note:'',metadata:{},strength:.5,weight:1,label:i<10?'informs':'',createdAt:ts,updatedAt:ts});}for(const [key,value]of Object.entries({onboardingComplete:true,physicsMode:'frozen',drift:false,camera:{x:690,y:450,zoom:1},visualTheme:'constellation',performanceMode:'battery',showStarfield:true,displayMode:'constellation'}))tx.objectStore('settings').put({key,value});await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()},{count,titles,types});await page.goto(base);await ready(page);}
async function ready(p){await p.waitForFunction(()=>window.ConstellationData?.getStatus().storageMode!=='starting'&&window.ConstellationData?.getStatus().onboardingComplete);await p.waitForTimeout(300)}
async function click(p,sel){await p.locator(sel).click();await p.waitForTimeout(220)}
async function snap(p,name){await p.waitForTimeout(250);await p.screenshot({path:path.join(out,name+'.png'),timeout:60000});results.screenshots.push(name);if(['desktop-empty','desktop-inspector','desktop-planner','desktop-knowledge','desktop-safety','mobile-inspector-390','light-planner'].includes(name)){const {default:AxeBuilder}=require('@axe-core/playwright');const a=await new AxeBuilder({page:p}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();results.accessibility.push({name,violations:a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}const bad=await p.evaluate(()=>[...document.querySelectorAll('button,input,select,textarea')].filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility==='visible'&&s.display!=='none'&&!e.closest('[aria-hidden="true"]')&&r.top>=0&&r.bottom<=innerHeight&&(r.right>innerWidth+2||r.left< -2)}).map(e=>({id:e.id,text:e.textContent.slice(0,35)})));if(bad.length)results.overflow.push({name,bad});console.log('SHOT',name)}
let base,browser;
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let p=await context.newPage();p.on('pageerror',e=>results.errors.push(e.message));await p.goto(base);await snap(p,'onboarding');await p.locator('#onboardingSkipBtn').click();await ready(p);await snap(p,'desktop-empty');await p.setViewportSize({width:390,height:844});await snap(p,'mobile-empty');await p.setViewportSize({width:1440,height:1000});
const legacyContext=await browser.newContext();const lp=await legacyContext.newPage();await lp.goto(base+'/seed');await lp.evaluate(()=>localStorage.setItem('constellation-thought-map-v1',JSON.stringify({nodes:[{id:'legacy-one',text:'A legacy thought',x:125,y:240,color:[100,170,150],created:1700000000000}],drift:false})));await lp.goto(base);await lp.waitForFunction(()=>window.ConstellationData?.getStatus().nodeCount===1);const legacy=await lp.evaluate(()=>ConstellationData.exportState());check('Legacy v1 migration preserves thought',legacy.nodes[0].title==='A legacy thought'&&legacy.nodes[0].position.x===125&&legacy.nodes[0].position.y===240);await lp.reload();await lp.waitForFunction(()=>window.ConstellationData?.getStatus().nodeCount===1);check('Legacy migration remains idempotent',true);await legacyContext.close();
const ids=await p.locator('[id]').evaluateAll(els=>els.map(e=>e.id));check('No duplicate DOM IDs',new Set(ids).size===ids.length,{count:ids.length});
await seed(p);check('Canonical IndexedDB v2 loaded',await p.evaluate(()=>ConstellationData.getStatus().nodeCount===20&&ConstellationData.getStatus().storageMode==='indexeddb'));
await snap(p,'desktop-graph');const before=await p.evaluate(()=>ConstellationData.exportState());fs.writeFileSync(path.join(out,'fixture-backup.json'),JSON.stringify(before));await p.reload();await ready(p);const after=await p.evaluate(()=>ConstellationData.exportState());check('Reload preserves node records',JSON.stringify(before.nodes)===JSON.stringify(after.nodes));check('Reload preserves edge records',JSON.stringify(before.edges)===JSON.stringify(after.edges));
await p.locator('#ideaInput').fill('Regression thought');await p.locator('#ideaInput').press('Enter');await p.waitForFunction(()=>ConstellationData.getStatus().nodeCount===21);check('Quick capture',true);await p.keyboard.press('Escape');await click(p,'#undoBtn');check('Undo restores count',await p.evaluate(()=>ConstellationData.getStatus().nodeCount===20));await click(p,'#redoBtn');check('Redo restores count',await p.evaluate(()=>ConstellationData.getStatus().nodeCount===21));
await click(p,'#desktopRail [data-ui-action=search]');await p.locator('#universalSearch').fill('The art of learning');await p.waitForTimeout(300);await p.locator('.search-result').first().click();await p.waitForTimeout(250);await snap(p,'desktop-inspector');if(!process.env.QA_SKIP_PANELS){for(const tab of ['details','appearance','media','relations','planning','knowledge']){await click(p,'#inspectorTabs [data-tab='+tab+']');await snap(p,'inspector-tab-'+tab)}}await click(p,'#inspectorTabs [data-tab=notes]');await p.locator('#nodeBodyEditor').fill('Edited research note.\n\nA durable thought with **meaning**.');await p.locator('#nodeBodyEditor').press('Tab');await p.waitForTimeout(600);await snap(p,'desktop-notes');
await click(p,'#inspectorTabs [data-tab=relations]');await p.locator('#pathTargetSelect').selectOption('fixture-4');await click(p,'#findPathBtn');await snap(p,'graph-path');await click(p,'#mobileInspectorCloseBtn');await p.locator('#scene').focus();await p.keyboard.press('Control+a');check('Keyboard multi-selection',await p.evaluate(()=>ConstellationData.getStatus().selectedCount===21));await snap(p,'multi-selection');await click(p,'#mobileInspectorCloseBtn');
if(!process.env.QA_SKIP_PANELS) for(const [action,id] of [['search','findPanel'],['organize','orgPanel'],['perspectives','perspectivePanel'],['planner','plannerPanel'],['knowledge','knowledgePanel'],['intelligence','intelligencePanel'],['creative','creativePanel'],['ecosystem','ecosystemPanel'],['insights','insightsPanel'],['transfer','interopPanel'],['safety','dataSheet'],['help','helpOverlay']]){
 await click(p,'#desktopRail [data-ui-action='+action+']');await snap(p,'desktop-'+action);
 const tabs=await p.locator('#'+id+' button[data-org-tab],#'+id+' button[data-planner-tab],#'+id+' button[data-knowledge-tab],#'+id+' button[data-intel-tab],#'+id+' button[data-creative-tab],#'+id+' button[data-eco-tab],#'+id+' button[data-insights-tab],#'+id+' button[data-interop-tab],#'+id+' button[data-data-tab],#'+id+' button[data-help-tab]').all();
 for(let i=0;i<tabs.length;i++){const tab=tabs[i],label=(await tab.textContent()).trim();await tab.click();await snap(p,'desktop-'+action+'-'+label.replace(/[^\w]+/g,'-'));}
 await p.keyboard.press('Escape');check(action+' closes with Escape',!(await p.locator('#'+id).evaluate(e=>e.classList.contains('open'))));
}
await p.keyboard.press('Control+k');await p.locator('#commandInput').fill('nonsense-no-match');await snap(p,'command-empty');await p.locator('#commandInput').fill('Add a thought');await p.keyboard.press('Enter');check('Keyboard command execution',await p.locator('#ideaInput').evaluate(e=>e===document.activeElement));
for(const view of ['timeline','outline','table','kanban','tasks','gallery']){await click(p,'#desktopRail [data-ui-action=perspectives]');await click(p,'[data-display='+view+']');await snap(p,'view-'+view);await click(p,'#viewBackCanvasBtn');}

for(const [tab,action]of [['research','bibliography'],['research','reading'],['research','evidence-view'],['study','recall'],['decisions','decision-view'],['genealogy','genealogy-view']]){await click(p,'#desktopRail [data-ui-action=knowledge]');await click(p,'[data-knowledge-tab='+tab+']');await click(p,'[data-k-action='+action+']');await snap(p,'view-'+action);await click(p,'#viewBackCanvasBtn');}
await click(p,'#desktopRail [data-ui-action=perspectives]');await click(p,'#addSceneBtn');await click(p,'#startPresentationBtn');await snap(p,'presentation');await click(p,'#presentationExitBtn');
await click(p,'#desktopRail [data-ui-action=help]');await click(p,'[data-help-tab=accessibility]');await click(p,'#highContrastBtn');await click(p,'#largeTargetsBtn');await p.locator('#uiScaleSelect').selectOption('large');await snap(p,'accessibility-large-contrast');await click(p,'#highContrastBtn');await click(p,'#largeTargetsBtn');await p.locator('#uiScaleSelect').selectOption('comfortable');await p.keyboard.press('Escape');await p.keyboard.press('F6');check('F6 moves keyboard focus',await p.evaluate(()=>document.activeElement!==document.body));
await click(p,'#canvasOptionsBtn');await p.locator('#visualThemeSelect').selectOption('light');await p.keyboard.press('Escape');await snap(p,'light-graph');await click(p,'#desktopRail [data-ui-action=planner]');await snap(p,'light-planner');await p.keyboard.press('Escape');await click(p,'#canvasOptionsBtn');await p.locator('#visualThemeSelect').selectOption('constellation');await p.keyboard.press('Escape');
for(const [w,h]of [[360,800],[390,844],[430,932],[844,390],[820,1180],[1180,820]]){await p.setViewportSize({width:w,height:h});await p.waitForTimeout(250);await click(p,'#fitBtn');await snap(p,'responsive-'+w+'x'+h);if(w<=760){await click(p,'#mobileNav [data-ui-action=more]');await snap(p,'mobile-more-'+w);await click(p,'#mobileToolSheet [data-ui-action=planner]');await snap(p,'mobile-planner-'+w);await p.keyboard.press('Escape');await click(p,'#mobileNav [data-ui-action=search]');await p.locator('#universalSearch').fill('The art');await p.waitForTimeout(200);await p.locator('.search-result').first().click();await click(p,'#inspectorTabs [data-tab=details]');await snap(p,'mobile-inspector-'+w);await click(p,'#inspectorTabs [data-tab=notes]');await click(p,'#noteFocusBtn');await snap(p,'mobile-notes-'+w);await p.keyboard.press('Escape');await click(p,'#mobileInspectorCloseBtn');if(w===390){await click(p,'#mobileNav [data-ui-action=search]');await snap(p,'mobile-find');await p.keyboard.press('Escape');await click(p,'#commandPaletteToolbarBtn');await snap(p,'mobile-command');await p.keyboard.press('Escape');await click(p,'#mobileNav [data-ui-action=more]');await click(p,'#mobileToolSheet [data-ui-action=knowledge]');await snap(p,'mobile-knowledge');await p.keyboard.press('Escape');await click(p,'#mobileNav [data-ui-action=add]');await snap(p,'mobile-quick-add');await p.keyboard.press('Escape');}}else{await click(p,'#desktopRail [data-ui-action=knowledge]');await snap(p,'tablet-knowledge-'+w);await p.keyboard.press('Escape');}}
await p.setViewportSize({width:1440,height:1000});await p.keyboard.press('Escape');await click(p,'#desktopRail [data-ui-action=safety]');await click(p,'[data-data-tab=backups]');await p.evaluate(()=>ConstellationData.createBackup());check('Backup created',await p.evaluate(async()=> (await ConstellationData.listBackups()).length>0));await p.keyboard.press('Escape');

// Export through the actual download, mutate the disposable fixture, then restore it through the preview UI.
await click(p,'#desktopRail [data-ui-action=transfer]');await click(p,'[data-interop-tab=export]');const downloadEvent=p.waitForEvent('download');await click(p,'#fullBackupExportBtn');const download=await downloadEvent;const backupPath=path.join(out,'downloaded-backup.json');await download.saveAs(backupPath);const saved=JSON.parse(fs.readFileSync(backupPath,'utf8'));check('Full backup download',saved.nodes.length===21);
await click(p,'[data-interop-tab=import]');await p.locator('#smartPasteInput').fill('{broken-json');await p.locator('#importFormatHint').selectOption('json');await click(p,'#analyzePasteBtn');check('Malformed import safely rejected',(await p.locator('#importPreviewTitle').textContent()).includes('Could not parse'));await snap(p,'import-error');
await p.locator('#smartPasteInput').fill('A temporary import');await p.locator('#importFormatHint').selectOption('text');await click(p,'#analyzePasteBtn');await p.locator('#importDestination').selectOption('current');await snap(p,'import-preview');await click(p,'#applyImportBtn');await p.waitForFunction(()=>ConstellationData.getStatus().nodeCount===22);check('Text import committed',true);await click(p,'#desktopRail [data-ui-action=search]');await p.locator('#universalSearch').fill('A temporary import');await p.waitForTimeout(300);await p.locator('.search-result').first().click();await click(p,'#deleteDetailBtn');await p.waitForFunction(()=>ConstellationData.getStatus().nodeCount===21);await click(p,'#desktopRail [data-ui-action=safety]');await click(p,'[data-data-tab=trash]');await snap(p,'trash-with-item');await click(p,'#trashList button:has-text("Restore")');await p.waitForFunction(()=>ConstellationData.getStatus().nodeCount===22);check('Trash restore',true);await p.keyboard.press('Escape');
await click(p,'#desktopRail [data-ui-action=transfer]');await click(p,'[data-interop-tab=import]');await p.locator('#importFileInput').setInputFiles(backupPath);await p.waitForFunction(()=>!document.querySelector('#restoreImportedBackupBtn').hidden);await click(p,'#restoreImportedBackupBtn');await click(p,'#restoreImportedBackupBtn');await p.waitForFunction(()=>ConstellationData.getStatus().nodeCount===21);const restored=await p.evaluate(()=>ConstellationData.exportState());check('Backup restores exact node payload',require('node:util').isDeepStrictEqual(restored.nodes,saved.nodes));check('Backup restores exact edge payload',require('node:util').isDeepStrictEqual(restored.edges,saved.edges));await p.keyboard.press('Escape');
// Real service-worker control and offline navigation, not a mocked response.
await p.reload();await ready(p);await p.waitForFunction(()=>!!navigator.serviceWorker.controller,{timeout:15000});await context.setOffline(true);await p.reload();await ready(p);check('Offline navigation and persisted graph',await p.evaluate(()=>ConstellationData.getStatus().nodeCount===21));await snap(p,'offline');await context.setOffline(false);
for(const count of [100,500,1000,2000,5000,10000]){const start=Date.now();await seed(p,count);await click(p,'#fitBtn');await p.waitForTimeout(1500);const stats=await p.evaluate(()=>ConstellationData.getStatus());check('Large graph '+count,stats.nodeCount===count);results.performance.push({count,loadAndSettleMs:Date.now()-start,fps:stats.fps,visibleNodes:stats.visibleNodes});if(count===2000)await snap(p,'dense-graph');}
check('Sampled accessibility checks',results.accessibility.every(a=>a.violations.length===0),results.accessibility);check('No uncaught page errors',results.errors.length===0,results.errors);check('No viewport control overflow',results.overflow.length===0,results.overflow);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({checks:results.checks.length,screenshots:results.screenshots.length,performance:results.performance},null,2));await browser.close();server.close();})().catch(async e=>{results.failure=e.stack;fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.error(e);if(browser){const pages=browser.contexts().flatMap(c=>c.pages());if(pages[0])await pages[0].screenshot({path:path.join(out,'failure.png'),timeout:10000}).catch(()=>{});await browser.close();}server.close();process.exitCode=1});
